### ISSUE TITLE
[Bug]: Incorrect detected scopes for installers

### ISSUE THREAD

**Issue by daiyam** [vedantmgoyal2009/winget-releaser#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

It seems that since few days that the scope of the installers are incorrectly detected:
- https://github.com/microsoft/winget-pkgs/pull/99163/files
- https://github.com/microsoft/winget-pkgs/pull/99119/files

Is it related to the update of Komac? If so it's an upstream bug.

**Comment by vedantmgoyal9** [comment]
cc @russellbanks

**Comment by russellbanks** [comment]
Sorry about this @daiyam. This took a long time to get to the bottom of but I've fixed this now, and added tests to ensure that it does not happen again. I will create a patch within the next day or so.

**Comment by vedantmgoyal9** [comment]
Fixed in https://github.com/russellbanks/Komac/releases/tag/v1.2.0

**Comment by daiyam** [comment]
@russellbanks In https://github.com/microsoft/winget-pkgs/pull/99592/files, the scopes are different but the installers became the same for both scopes. The scopes should have different installers.

Here the previous successful PR: https://github.com/microsoft/winget-pkgs/pull/98656/files

**Comment by russellbanks** [comment]
I can't seem to reproduce this @daiyam. I've attached the output below that shows it successful for me locally. I wonder whether this is down to the installer urls that winget releaser has passed to Komac but winget releaser doesn't output that currently. I have created https://github.com/vedantmgoyal2009/winget-releaser/issues/119 to ask for this.

```
java -jar komac-1.2.0-all.jar up --id VSCodium.VSCodium --version 1.76.1.23069 --urls https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumUserSetup-ia32-1.76.1.23069.exe,https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumSetup-ia32-1.76.1.23069.exe,https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumUserSetup-x64-1.76.1.23069.exe,https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumSetup-x64-1.76.1.23069.exe,https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumUserSetup-arm64-1.76.1.23069.exe,https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumSetup-arm64-1.76.1.23069.exe
Found VSCodium.VSCodium in the winget-pkgs repository
Found latest version: 1.76.0.23062
A pull request for VSCodium.VSCodium 1.76.1.23069 was created on Sun Mar 12 18:04:24 GMT 2023
https://github.com/microsoft/winget-pkgs/pull/99264
Would you like to proceed? [y/n]: y
```

```yaml
# Created with Komac v1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: VSCodium.VSCodium
PackageVersion: 1.76.1.23069
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
ReleaseDate: 2023-03-10
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumUserSetup-ia32-1.76.1.23069.exe
  InstallerSha256: 694E842B017AD4B561678CE76514D8DABBBF217DD2D0F0958388D1CB59C7A53A
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumSetup-ia32-1.76.1.23069.exe
  InstallerSha256: 51FEDF41ACE8076ED3265F391C3A14B9AA3A26D495DA42A02991A61E061E2465
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumUserSetup-x64-1.76.1.23069.exe
  InstallerSha256: 880D0817DCE45AEA0D6E8A75A8031D614EA0CFD4E0188D4EEA06E402A293AEEA
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumSetup-x64-1.76.1.23069.exe
  InstallerSha256: 7CC8CF210AD9B7ED90EB3252A098809290B2985717504A3D1F4A0B645AD3D0F2
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumUserSetup-arm64-1.76.1.23069.exe
  InstallerSha256: 9BB96AD884BF85B7ED14C82E40F41CD6E5F4FE27B456E4E0F6FADBBB246B70BA
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.1.23069/VSCodiumSetup-arm64-1.76.1.23069.exe
  InstallerSha256: BA292F51CCFF55729B1EA0178B935CD2E283E277AF98CB62B01118E9B81019B8
ManifestType: installer
ManifestVersion: 1.4.0

# Created with Komac v1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: VSCodium.VSCodium
PackageVersion: 1.76.1.23069
PackageLocale: en-US
Publisher: VSCodium
PublisherUrl: https://github.com/VSCodium/vscodium
PublisherSupportUrl: https://github.com/VSCodium/vscodium/issues
Author: VSCodium
PackageName: VSCodium
PackageUrl: https://vscodium.com
License: MIT
LicenseUrl: https://github.com/VSCodium/vscodium/blob/master/LICENSE
Copyright: Copyright (c) 2022 VSCodium Team
CopyrightUrl: https://github.com/VSCodium/vscodium/blob/master/LICENSE
ShortDescription: VSCodium is a community-driven, freely-licensed and telemetry-free rebuilt of Microsoft's Visual Studio Code.
Description: |-
  VSCodium is a community-driven, freely-licensed and telemetry-free rebuilt of Microsoft's Visual Studio Code.
  VSCodium is a powerful IDE which runs on your desktop and is available for Windows, macOS and Linux.
Tags:
- cross-platform
- editor
- foss
- ide
- javascript
- open-source
- typescript
- vscode
ReleaseNotesUrl: https://github.com/VSCodium/vscodium/releases/tag/1.76.1.23069
ManifestType: defaultLocale
ManifestVersion: 1.4.0

# Created with Komac v1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: VSCodium.VSCodium
PackageVersion: 1.76.1.23069
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
```

**Comment by russellbanks** [comment]
In case it is a bug that I've (unintentionally) fixed since 1.2.0, I'll be releasing Komac 1.3.0 today or tomorrow.

**Comment by daiyam** [comment]
@russellbanks The run https://github.com/VSCodium/vscodium/actions/runs/4476774491/jobs/7868550697 has the full command line:
`java -jar komac.jar update --id 'VSCodium.VSCodium.Insiders' --version 1.77.0.23080 --urls 'https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-arm64-1.77.0.23080-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-ia32-1.77.0.23080-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-x64-1.77.0.23080-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumUserSetup-arm64-1.77.0.23080-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumUserSetup-ia32-1.77.0.23080-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumUserSetup-x64-1.77.0.23080-insider.exe' --submit`

but the output is still having the issue:
```
# Created with WinGet Releaser v2 using Komac v1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: VSCodium.VSCodium.Insiders
PackageVersion: 1.77.0.23080
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2023-03-21
Installers:
- Architecture: x86
Scope: user
InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-ia32-1.77.0.23080-insider.exe
InstallerSha256: 1C994CFDDDD81359196E82A08CD883ABA620B4193C24A82F8AAE5E22947E7BA5
- Architecture: x86
Scope: machine
InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-ia32-1.77.0.23080-insider.exe
InstallerSha256: 1C994CFDDDD81359196E82A08CD883ABA620B4193C24A82F8AAE5E22947E7BA5
- Architecture: x64
Scope: user
InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-x64-1.77.0.23080-insider.exe
InstallerSha256: E0F87F56CAB9BDF4A3701723913645F4FF95263978A03B30F719F21CD5B7EAAB
- Architecture: x64
Scope: machine
InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-x64-1.77.0.23080-insider.exe
InstallerSha256: E0F87F56CAB9BDF4A3701723913645F4FF95263978A03B30F719F21CD5B7EAAB
- Architecture: arm64
Scope: user
InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-arm64-1.77.0.23080-insider.exe
InstallerSha256: 7613D749D66CAE5640ED7A786396B95BB5A40CF5AB0658B6785C222402045F5E
- Architecture: arm64
Scope: machine
InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-arm64-1.77.0.23080-insider.exe
InstallerSha256: 7613D749D66CAE5640ED7A786396B95BB5A40CF5AB0658B6785C222402045F5E
ManifestType: installer
ManifestVersion: 1.4.0

# Created with WinGet Releaser v2 using Komac v1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: VSCodium.VSCodium.Insiders
PackageVersion: 1.77.0.23080
PackageLocale: en-US
Publisher: VSCodium
PublisherUrl: https://github.com/VSCodium/vscodium
PublisherSupportUrl: https://github.com/VSCodium/vscodium/issues
Author: VSCodium
PackageName: VSCodium Insiders
PackageUrl: https://vscodium.com
License: MIT
LicenseUrl: https://github.com/VSCodium/vscodium/blob/master/LICENSE
Copyright: Copyright (c) 2022 VSCodium Team
CopyrightUrl: https://github.com/VSCodium/vscodium/blob/master/LICENSE
ShortDescription: VSCodium is a community-driven, freely-licensed and telemetry-free rebuilt of Microsoft's Visual Studio Code Insiders.
Description: |-
VSCodium is a community-driven, freely-licensed and telemetry-free rebuilt of Microsoft's Visual Studio Code Insiders.
VSCodium is a powerful IDE which runs on your desktop and is available for Windows, macOS and Linux.
Tags:
- cross-platform
- editor
- foss
- ide
- javascript
- open-source
- typescript
- vscode
ReleaseNotesUrl: https://github.com/VSCodium/vscodium-insiders/releases/tag/1.77.0.23080-insider
ManifestType: defaultLocale
ManifestVersion: 1.4.0

# Created with WinGet Releaser v2 using Komac v1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: VSCodium.VSCodium.Insiders
PackageVersion: 1.77.0.23080
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
```

**Comment by russellbanks** [comment]
Thanks for getting back @daiyam. I'll see if I can reproduce the issue by running that command with the 1.2.0 jar compared to 1.3.0 jar. It could be a fix that I've unintentionally done since 1.2.0 or it could be something more.

Edit: I've reproduced this and am working on a fix. I will make a release once it is fixed.

**Comment by russellbanks** [comment]
Hi @daiyam, sorry for the issues here. Urls on the command line are pretty difficult to deal with because they're not matched up to anything unlike if it were inputted as a prompt. This means that there has to be a matching algorithm that takes all the data it can from the installers and match it up to the previous ones.

I don't currently know a safe and reliable way to programatically tell whether an installer installs in user or machine scope, so it resorts to checking the url. Luckily the VSCodium binaries contain `User` in the user-scope installers, which is what allows Komac to just about match it all correctly.

I had changed the algorithm to match installers in 1.2.0 to be shorter, but as you can see it has caused an inconsistency. I've replaced it with the matching algorithm from 1.1.0 and it works for this case now. I'll be releasing 1.3.0 soon with this fix.

With 1.1.0 algorithm now back in 1.3.0:
```yaml
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumUserSetup-ia32-1.77.0.23080-insider.exe
  InstallerSha256: 22DA0D96151E4BF808BF720341132573DEE8C9C2EA8A6C223E519E75586FC581
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-ia32-1.77.0.23080-insider.exe
  InstallerSha256: 1C994CFDDDD81359196E82A08CD883ABA620B4193C24A82F8AAE5E22947E7BA5
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumUserSetup-x64-1.77.0.23080-insider.exe
  InstallerSha256: C42167421848A242CBF567B7D5CDEC7798A049E1C93E72CB3FEC5D57FD773B6D
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-x64-1.77.0.23080-insider.exe
  InstallerSha256: E0F87F56CAB9BDF4A3701723913645F4FF95263978A03B30F719F21CD5B7EAAB
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumUserSetup-arm64-1.77.0.23080-insider.exe
  InstallerSha256: C79166AEAA98E7BB9936ADAC3014C1CA4BAE085007A24C1B90201D7A3F624205
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23080-insider/VSCodiumSetup-arm64-1.77.0.23080-insider.exe
  InstallerSha256: 7613D749D66CAE5640ED7A786396B95BB5A40CF5AB0658B6785C222402045F5E
```

Edit: Komac 1.3.0 has been released! WinGet Releaser should update itself soon.
