### ISSUE TITLE
[Question]: Actions failed with "Number of InstallerUrls are not equal".

### ISSUE THREAD

**Issue by sprout2000** [vedantmgoyal2009/winget-releaser#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

my `.github/workflows/winget.yml` failed as follows:

```sh
Update manifests and create pull request
  Found Existing Version: 1.10.1
  Exception: D:\a\leafview\leafview\winget-pkgs\Tools\YamlCreate.ps1:[9](https://github.com/sprout2000/leafview/actions/runs/3011186300/jobs/4838048413#step:2:10)15
  Line |
   915 |      Throw 'Number of InstallerUrls are not equal'
       |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       | Number of InstallerUrls are not equal
  
  node:child_process:826
      err = new Error(msg);
            ^
  
  Error: Command failed: .\YamlCreate.ps1 '{"PackageIdentifier":"sprout2000.LeafView","PackageVersion":"1.10.5","InstallerUrls":[],"ReleaseNotesUrl":"https://github.com/sprout2000/leafview/releases/tag/v1.10.5","ReleaseDate":"2022-09-07","DeletePreviousVersion":false}'
      at checkExecSyncError (node:child_process:826:11)
      at execSync (node:child_process:900:15)
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9774:3
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 6136,
    stdout: null,
    stderr: null
  }
```

It used to pass without any problems, but now it fails.
Could you tell me what to do about it?

Here's my `winget.yml`:
```yaml
name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: sprout2000.LeafView
          token: ${{ secrets.WINGET_TOKEN }}
```
