### ISSUE TITLE
[Feature/Idea]:  Add support for installer dependencies

### ISSUE THREAD

**Issue by licon4812** [vedantmgoyal2009/winget-releaser#292]
### What would you like to see changed/added?

Winget now supports the declaration and installation of dependencies in the manifests. Is this something we can look into for this github action?

Example Manifest with Dependencies:

```yaml
# Created with YamlCreate.ps1 v2.2.12 $debug=NVS1.CRLF.5-1-22621-2506.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: tbillington.kondo
PackageVersion: "0.8"
InstallerLocale: en-US
InstallerType: zip
Commands:
- kondo
ReleaseDate: 2023-12-19
Installers:
- Architecture: x86
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: kondo.exe
    PortableCommandAlias: kondo
  InstallerUrl: https://github.com/tbillington/kondo/releases/download/v0.8/kondo-x86_64-pc-windows-msvc.zip
  InstallerSha256: 36FB33D71CE6896BFBC0A5F26809AD1BE986EFE9C5C887BA9D3955D8CDEE7895
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.VCRedist.2015+.x86
        InstallerType: exe
        InstallerUrl: https://aka.ms/vs/16/release/vc_redist.x86.exe
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: kondo.exe
    PortableCommandAlias: kondo
  InstallerUrl: https://github.com/tbillington/kondo/releases/download/v0.8/kondo-x86_64-pc-windows-msvc.zip
  InstallerSha256: 36FB33D71CE6896BFBC0A5F26809AD1BE986EFE9C5C887BA9D3955D8CDEE7895
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.VCRedist.2015+.x64
        InstallerType: exe
        InstallerUrl: https://aka.ms/vs/16/release/vc_redist.x64.exe

ManifestType: installer
ManifestVersion: 1.5.0

```
