### ISSUE TITLE
[Bug]: Invoke-RestMethod fail

### ISSUE THREAD

**Issue by flick9000** [vedantmgoyal2009/winget-releaser#316]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

Workflow fails with this error:

```
    3 |  $ReleaseInfo = Invoke-RestMethod `
     |                 ~~~~~~~~~~~~~~~~~~~
     |  {   "message": "Not Found",   "documentation_url":
     | "https://docs.github.com/rest/releases/releases#get-a-release-by-tag-name",   "status": "404" }
Error: Process completed with exit code 1.
```

Tag name is v1.1.4

Workflow file:
```

name: Publish to WinGet

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["publish"]
    types: [completed]
  

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: flick9000.WinScript
          max-versions-to-keep: 3 # keep only latest 5 versions
          installers-regex: '\.exe$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}
```

**Comment by vedantmgoyal9** [comment]
Hi,

On `workflow_run ` event, both `github.event.release.tag_name` and `github.ref_name` are empty, so you'll have to provide tag manually. For example, you can do:

```yml
- name: Get latest release tag name
  id: get-latest-release
  run: |
    "tag=$((gh api repos/${{ github.repository }}/releases/latest | ConvertFrom-Json).tag_name)" >> $env:GITHUB_OUTPUT
  shell: pwsh
- uses: vedantmgoyal9/winget-releaser@main
  with:
    release-tag: ${{ steps.get-latest-release.outputs.tag }}
```

Reference (action.yml):
```yml
release-tag:
    required: true
    description: The release tag to be used for creating manifests.
    default: ${{ github.event.release.tag_name || github.ref_name }}
```

**Comment by vedantmgoyal9** [comment]
Hi @flick9000,

On `workflow_run` event, both `github.event.release.tag_name` and `github.ref_name` are empty, so you'll have to provide tag manually. For example, you can do:

```yml
- name: Get latest release tag name
  id: get-latest-release
  run: |
    "tag=$((gh api repos/${{ github.repository }}/releases/latest | ConvertFrom-Json).tag_name)" >> $env:GITHUB_OUTPUT
  shell: pwsh
- uses: vedantmgoyal9/winget-releaser@main
  with:
    release-tag: ${{ steps.get-latest-release.outputs.tag }}
```

Reference (action.yml):
```yml
release-tag:
    required: true
    description: The release tag to be used for creating manifests.
    default: ${{ github.event.release.tag_name || github.ref_name }}
```
